## GENERATED by scripts/codegen_card_db.py — DO NOT EDIT BY HAND.
## Source: data/cards/military.yaml (conscript_pool + elite_units).
##
## Weight → count 해석 (2026-04-21 해석 B):
##   BASE 에서 동등 확률로 1 항목 선택 → 해당 항목의 count 만큼 유닛 추가.
##   R4 카드 징집: ENHANCED_MAP 으로 변환. R10: ELITE_UNITS 에서 1기 추가.
class_name ConscriptPoolData
extends RefCounted


const BASE: Array = [
	{"id": "ml_recruit", "count": 3},
	{"id": "ml_drone", "count": 2},
	{"id": "ml_biker", "count": 2},
	{"id": "ml_infantry", "count": 1},
	{"id": "ml_shield", "count": 1},
	{"id": "ml_plasma", "count": 1},
]

const ELITE_UNITS: Array[String] = [
	"ml_sniper",
	"ml_artillery",
	"ml_walker",
	"ml_commander",
]
